### ISSUE TITLE
Error reading tile names from cfg

### ISSUE THREAD

**Issue by rkanavath** [CNES/S1Tiling#2]
>  Tiles: 33NWB,33NWC
Passing list of tile names in "Tiles" key of S1Processor.cfg isn't working.

Flawed code is here: https://github.com/CNES/S1Tiling/blob/master/S1Processor.py#L101

Below diff fixes it:

```diff
-           self.tiles_list = [s.strip() for s in tiles.split(", ")]
+           self.tiles_list = [s.strip() for s in tiles.split(',')]
```

**Comment by koleckt** [comment]
Master branch corrected
