### ISSUE TITLE
Config S1Tiling

### ISSUE THREAD

**Issue by BasileGoussard** [CNES/S1Tiling#4]
Hello, 

Do you know where I can find a "tutorial" of S1Tiling ?

Thank you,
Best regards,
Basile

**Comment by koleckt** [comment]
Dear Basile,

The current version of S1Tiling is not well documented.
We are working hard to develop of new version with the user documentation.

For running the code you need Python2, numpy, scipy, PIL.
You need also to install OrfeoToolBox https://www.orfeo-toolbox.org/
The code can also download S1 images from PEPS (peps.cnes.fr) if you have an account.
If you want to use the multitemporal speckle filtering (option of S1Tiling) you have also to compile the OTB application SARMultitempFiltering
The config file (.cfg) which is the input file of the code is the only thing you have to fill.


I can help you to do all this step, while the documentation in not available

**Comment by BasileGoussard** [comment]
Hello @koleckt ,
Thank you very much for your answer. 
Actually,  I managed to do it by using OTB & some python scripts.

I'looking forward to test the new version of S1Tiling.
Best regards,
Basile
